name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code ex
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask_docker:latest

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name flask_docker ${{ secrets.DOCKER_USERNAME }}/flask_docker:latest

    - name: Wait for Flask app to start
      run: sleep 20  # Adjust the sleep duration if needed

    - name: Print Docker container logs
      run: docker logs flask_docker

    - name: Test Flask App
      run: |
       curl -X POST -H "Content-Type: application/json" -d '{ "age": 29,"bmi": 30.5,"children": 2,"sex": 1,"smoker": 0,"region": 3}' http://127.0.0.1:5000/predict
